version: '3.9'
services:
  db:
    container_name: somnar-db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ../data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: somnar